name: winot
version: '0.1.0.0'
synopsis: keep your laptop connected to wifi at all times on OpenBSD
description: Please see README.md
category: Networking
author: Scott Bonds
maintainer: scott@ggr.com
copyright: 2016 Scott Bonds
license: ISC
github: bonds/winot
homepage: http://github.com/bonds/winot#readme
tested-with: GHC==7.10.3
dependencies:
- liquidhaskell-cabal
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  exposed-modules:
  - Util.Log
  - Util.Misc
  - Util.Run
  - Util.Orphan
  - Status.Config
  - Status.Filter
  - Status.Interface
  - Status.Lease
  - Status.Process
  - Status.Route
  - Status.Connection
  - Action.Connect
  - Loop
  - World
  dependencies:
  - base >=4.6 && <4.10
  - safe >=0.3 && <0.4
  - async >=2.1 && <2.2
  - deepseq >=1.3 && <=1.5
  - containers >=0.5 && <0.6
  - semiring-simple >=1.0 && <1.1
  - mtl >=2.1 && <2.3
  - transformers >=0.4 && <0.6
  - text >=1.2 && <1.3
  - string-conv >=0.1 && <0.2
  - bytestring >=0.10 && <0.11
  - hslogger
  - unbounded-delays
  - stm
  - process
  - clock
  - htoml
  - parsec
  - unordered-containers
  - string-conversions
  - text-icu
  - monad-loops
  - extra
  - threads
  - unix
  - aeson
  - aeson-pretty
  - directory
  - protolude
  - trifecta
  - monad-logger
  - fast-logger
  - unix-time
  - template-haskell
  - system-filepath
  - ip
executables:
  winot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - base >=4.6 && <4.10
    - safe >=0.3 && <0.4
    - async >=2.1 && <2.2
    - deepseq >=1.3 && <=1.5
    - containers >=0.5 && <0.6
    - semiring-simple >=1.0 && <1.1
    - mtl >=2.1 && <2.3
    - transformers >=0.4 && <0.6
    - text >=1.2 && <1.3
    - string-conv >=0.1 && <0.2
    - bytestring >=0.10 && <0.11
    - winot
    - protolude
    - monad-logger
tests:
  winot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - winot
    - HUnit
    - text
    - QuickCheck
flags:
  liquidhaskell:
    description: After building, verify with LiquidHaskell
    manual: false
    default: false
