#!/bin/sh
#
# $OpenBSD: winot,v 1.0 2015/09/13 00:35:04 bonds Exp $

daemon="GEM_PATH=/home/scott/.rbenv/versions/2.2/lib/ruby/gems/2.2 PATH=/home/scott/.rbenv/shims:/home/scott/.rbenv/bin:/usr/local/bin:/usr/bin:/sbin /usr/local/bin/winot"

. /etc/rc.d/rc.subr

pexp=".*/usr/local/bin/winot"

rc_bg=YES
rc_reload=NO
rc_cmd $1
